/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author flash
 */
import java.util.ArrayList;
import java.util.Random;

public class ex1p2_miguelmoran extends javax.swing.JFrame {

    /**
     * Creates new form ex1p2_miguelmoran
     */
    Random rng = new Random();
    Usuario usuario0 = new Usuario("Usuario");
    ArrayList<Usuario> usuarios = new ArrayList<>();
    int usuario = 0;

    public ex1p2_miguelmoran() {
        usuarios.add(usuario0);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        Terminal_TextArea = new javax.swing.JTextArea();
        Enter_Button = new javax.swing.JButton();
        Usuario_Label = new javax.swing.JLabel();
        Creaciones_ComboBox = new javax.swing.JComboBox<>();
        Visualizar_Button = new javax.swing.JButton();
        Command_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Terminal_TextArea.setEditable(false);
        Terminal_TextArea.setColumns(20);
        Terminal_TextArea.setRows(5);
        ScrollPane.setViewportView(Terminal_TextArea);

        Enter_Button.setBackground(new java.awt.Color(0, 204, 204));
        Enter_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Enter_Button.setForeground(new java.awt.Color(0, 0, 0));
        Enter_Button.setText("Enter");
        Enter_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_ButtonActionPerformed(evt);
            }
        });

        Usuario_Label.setBackground(new java.awt.Color(0, 204, 204));
        Usuario_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Usuario_Label.setForeground(new java.awt.Color(0, 0, 0));
        Usuario_Label.setText("> Usuario");
        Usuario_Label.setOpaque(true);

        Creaciones_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home" }));

        Visualizar_Button.setBackground(new java.awt.Color(255, 153, 153));
        Visualizar_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Visualizar_Button.setForeground(new java.awt.Color(0, 0, 0));
        Visualizar_Button.setText("Visualizar");

        Command_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Command_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Creaciones_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Usuario_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Command_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Enter_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Visualizar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Usuario_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Command_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Enter_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Creaciones_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Visualizar_Button))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Command_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Command_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Command_TextFieldActionPerformed

    private void Enter_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_ButtonActionPerformed
        if (Validacion()) {
            String comando = ObtenerFuncion();
            switch (comando) {
                case "clear" -> {
                    clear();
                }
                case "ls" -> {
                    ls();
                }
                case "mkdir" -> {
                    mkdir();
                }
                case "boroa create" -> {
                    boroa_create();
                }
                case "boroa chnge" -> {
                    boroa_chnge();
                }
                default -> {
                    Terminal_TextArea.append(Command_TextField.getText() + "\n");
                    Terminal_TextArea.append(">> Comando no reconocido \n");
                    Command_TextField.setText("");
                }
            }
            Command_TextField.setText("");
        } else {
            Terminal_TextArea.append(Command_TextField.getText());
            Terminal_TextArea.append(">> Comando no reconocido");
            Command_TextField.setText("");
        }

    }//GEN-LAST:event_Enter_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex1p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex1p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex1p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex1p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex1p2_miguelmoran().setVisible(true);
            }
        });
    }

    public String ObtenerNombre() {
        String[] comps = Command_TextField.getText().split(" ");
        return comps[comps.length - 1];
    }

    public String ObtenerFuncion() {
        String funcion = "";
        String[] comps = Command_TextField.getText().split(" ");
        if (comps.length > 2) {
            funcion += comps[0];
            funcion += " ";
            funcion += comps[1];
        } else {
            funcion = comps[0];
        }
        return funcion;
    }

    public boolean Validacion() {
        boolean valido = true;
        int ascii = 0;
        if (Command_TextField.getText().contains("  ")) {
            valido = false;
        }
        return valido;
    }

    public void clear() {
        Terminal_TextArea.setText("cleared");
    }

    public void ls() {
        Terminal_TextArea.append(Command_TextField.getText() + "\n");
        for (int i = usuarios.get(usuario).getCreaciones().size(); i > 0; i--) {
            Terminal_TextArea.append(">> " + usuarios.get(usuario).getNombreCreacion(i));
        }
    }

    public void mkdir() {
        String string = "";
        for (int i = Command_TextField.getText().length() - 5; i < Command_TextField.getText().length(); i++) {
            string += Command_TextField.getText().charAt(i);
        }
        if (string.equals(".file")) {
            String rand_string = "";
            for (int i = 0; i < 20; i++) {
                int random = rng.nextInt(123);
                char random_char = (char) random;
                rand_string += random_char;
            }
            Archivo archivo = new Archivo(rand_string, ObtenerNombre());
            usuarios.get(usuario).getCreaciones().addLast(archivo);
        } else {
            Directorio directorio = new Directorio(ObtenerNombre());
            usuarios.get(usuario).getCreaciones().addLast(directorio);
        }
        Creaciones_ComboBox.addItem(ObtenerNombre());
        Terminal_TextArea.append(Command_TextField.getText() + "\n");
    }

    public void rm() {
        String string = "";
        for (int i = Command_TextField.getText().length() - 5; i < Command_TextField.getText().length(); i++) {
            string += Command_TextField.getText().charAt(i);
        }
        if (string.equals(".file")) {
            int pos = -1;
            for (int i = 0; i < usuarios.get(usuario).getCreaciones().size(); i++) {
                if (usuarios.get(usuario).getCreaciones().get(i).getNombre().equals(ObtenerNombre())) {
                    pos = i;
                    break;
                }
            }
            usuarios.get(usuario).getCreaciones().remove(pos);
        } else if (string.equals("")) {
            Terminal_TextArea.append(">> archivo o directorio no encontrado");
        } else {
            Directorio directorio = new Directorio(Command_TextField.getText());
            usuarios.get(usuario).getCreaciones().remove(directorio);
        }
        Creaciones_ComboBox.removeItem(string);
        Terminal_TextArea.append(Command_TextField.getText() + "\n");
    }

    public void boroa_create() {
        boolean exist = false;
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getNombre().equals(ObtenerNombre())) {
                usuario = i;
                exist = true;
            }
        }
        if (exist) {
            Terminal_TextArea.append(Command_TextField.getText() + "\n");
            Terminal_TextArea.append(">> usuario ya existe \n");
        } else {
            Usuario usuario = new Usuario(ObtenerNombre());
            usuarios.addLast(usuario);
            Directorio directorio = new Directorio("Home");
            usuarios.getLast().getCreaciones().add(directorio);
            Terminal_TextArea.append(Command_TextField.getText());
        }
    }

    public void boroa_chnge() {
        boolean exist = true;
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getNombre().equals(ObtenerNombre())) {
                usuario = i;
                exist = false;
            }
        }
        if (exist) {
            Terminal_TextArea.append(">> usuario no encontrado \n");
        } else {
            Usuario_Label.setText("> " + usuarios.get(usuario).getNombre());
            Terminal_TextArea.append(Command_TextField.getText() + "\n");
            Creaciones_ComboBox.removeAllItems();
            for (int i = 0; i < usuarios.get(usuario).getCreaciones().size(); i++) {
                Creaciones_ComboBox.add(usuarios.get(usuario).getCreaciones().getNombre());
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Command_TextField;
    private javax.swing.JComboBox<String> Creaciones_ComboBox;
    private javax.swing.JButton Enter_Button;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextArea Terminal_TextArea;
    private javax.swing.JLabel Usuario_Label;
    private javax.swing.JButton Visualizar_Button;
    // End of variables declaration//GEN-END:variables
}
